routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('producto', 'ProductoController');
Route::resource('usuario', 'UserController');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/busqueda','ProductoController@buscar')->name('producto.search');
Route::post('/compra/{id}','VentaController@addProducto')->name('venta.producto');
Route::get('/detalle/{id}','VentaController@viewProducto')->name('venta.detalle');
Route::resource('venta', 'VentaController');

resources/views/usuario/perfil.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: AlexisCruz
 * Date: 01/12/2018
 * Time: 18:23
 */
?>

@extends ('layouts.tema')
@section('contenido')
<div >
<h2> Hola mundo {{ Auth::user()->name }}</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <table>
            <thead>
            <tr>
                <th>  </th>
                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Precio</th>
            </tr>
            </thead>

            <tbody>
            @foreach($producto as $prod)
                <tr>
                    <td>
                        <a class="btn btn-sm bt-info btn-primary" href ="{{route('producto.show', $prod->id)}}"> Ver Detalles </a>
                    </td>

                    <td>{{ $prod->nombre }}</td>
                    <td>{{ $prod->descripcion }} </td>
                    <td>{{ $prod->precio }} </td>
                    <td>
                        <img src="/img/productos/{{$prod->photo}}" alt="imagen producto" class="w3->round">
                    </td>
                </tr>

            @endforeach
            </tbody>
        </table>
    </div>

</div>
@endsection