routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('producto', 'ProductoController');
Route::resource('usuario', 'UserController');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/busqueda','ProductoController@buscar')->name('producto.search');
Route::post('/compra/{id}','VentaController@addProducto')->name('venta.producto');
Route::get('/detalle/{id}','VentaController@viewProducto')->name('venta.detalle');
Route::resource('venta', 'VentaController');

app/Venta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Venta extends Model
{
	protected $primaryKey = 'idVenta';

    public function productos(){
    	return $this->belongsToMany(Producto::class, 'producto_venta', 'venta_id', 'producto_id');
    }
    public function Users(){
    	return $this->belongsToMany(User::Class);
    }

}

app/Http/Controllers/VentaController.php
<?php

namespace App\Http\Controllers;
use Carbon\Carbon;

use App\Venta;
use App\Producto;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class VentaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$ventas= Venta::all();
        //$user = User::find(\Auth::id());

        $ventas = Venta::where('idUsuario', \Auth::id())->with('productos')->get();
        
        return view('ventas.indexVentas', compact('ventas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ventas.formVentas');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $now =  Carbon::now();
       
        $ventas = new Venta();
        $ventas->fecha = $now->format('Y-m-d');
        $ventas->total = $request->total;
        $ventas->idUsuario= $request->usuario;
        $ventas->save();

        return redirect()->route('venta.index');
            

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Venta  $venta
     * @return \Illuminate\Http\Response
     */
    public function show(Venta $venta)
    {

       return view('ventas.showVentas', compact('venta'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Venta  $venta
     * @return \Illuminate\Http\Response
     */
    public function edit(Venta $venta)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Venta  $venta
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Venta $venta)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Venta  $venta
     * @return \Illuminate\Http\Response
     */
    public function destroy(Venta $venta)
    {
        //
    }

    public function addProducto(Request $request, $id){
        
        $producto = Producto::find($id);
        $user = User::find(\Auth::id());

         $now =  Carbon::now();
       
        $ventas = new Venta();        

        $ventas->fecha = $now->format('Y-m-d');
        $ventas->total = $producto->precio;
        $ventas->idUsuario= $user->id;
        
        $ventas->save();



        $ventas->Productos()->attach($producto);

        return redirect()->route('venta.index');
    }

    public function viewProducto(Request $request, $id){
        $producto = Producto::find($id);

        return view ('productos.showProductos', compact('producto'));
    }
}

resources/views/ventas/formVentas.blade.php
@extends ('layouts.tema')
@section('contenido')

    <div class="row">
      <div clas="col-md-12">
          <div class="tile">
          <form action="{{ route('venta.store') }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
             <!--
             <div class="form-group">
                <label for="idAlumno">ID</label>
                <input name="idAlumno"class="form-control" type="text">
             </div>
            -->
            
             <div class="form-group">
                <label for="total">Total</label>
                <input name ="total" class="form-control" type="text">
             </div>
               <div class="form-group">
                <label for="usuario">Usuario</label>
                <input name ="usuario" class="form-control" type="text">
             </div>
            
             
            <div class="tile-footer">
              <button class="btn btn-primary" type="submit">Agregar</button>
            </div>
             
            
          </form>
        </div>
      </div>
    </div>

@endsection
    

resources/views/ventas/indexVentas.blade.php
@extends ('layouts.tema')
@section('contenido')

<div class="row">
  <div class="col-md-12">
    <table>
      <thead>
        <tr>
          <th>  </th>
          <th>ID</th>
          <th>Usuario</th>
          <th>Fecha</th>
          <th>Total</th>

        </tr>
      </thead>

      <tbody>
        @foreach($ventas as $vent)
          <tr>
            <td>
              <a class="btn btn-sm bt-info btn-primary" href ="{{route('venta.detalle', $vent->productos->first()->id)}}"> Ver Detalles </a>
            </td>

            <td>{{ $vent->idVenta}}</td>  
            <td>{{ $vent->idUsuario }} </td>
            <td>{{ $vent->fecha }} </td> 
            <td>{{ $vent->total }} </td> 
            
          </tr>
          
        @endforeach
      </tbody>
    </table>
  </div>

</div>

@endsection

resources/views/ventas/showVentas.blade.php
@extends ('layouts.tema')
@section('contenido')
<div class="row">
  <div class="col-md-12">
    <table>
      <thead>
        <tr>
          <th>ID </th>
          <th>Usuario</th>
          <th>Fecha</th>
          <th>Total</th>
        </tr>
      </thead>

      <tbody>
          <tr>

            <td>{{ $venta->idVentas}}</td>
            <td>{{ $venta->idUsuario }}</td>
            <td>{{ $venta->fecha }}</td>
            <td>{{ $venta->total }}</td>
           
          </tr>
        
      </tbody>
    </table>

    <!-- tiene que mandarte a ventas con el formulario-->
      <input type="hidden" name="_method" value="Comprar">
      <button type="submit" class="btn btn-danger">Comprar</button>
  </div>

</div>

@endsection