routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('producto', 'ProductoController');
Route::resource('usuario', 'UserController');
Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/busqueda','ProductoController@buscar')->name('producto.search');
Route::post('/compra/{id}','VentaController@addProducto')->name('venta.producto');
Route::get('/detalle/{id}','VentaController@viewProducto')->name('venta.detalle');
Route::resource('venta', 'VentaController');

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    protected $fillable =['nombre','descripcion', 'cantidad', 'existencia', 'precio', 'photo'];

    public function Ventas(){
    	return $this->belongsToMany(Venta::class);
    }

    public function Compras(){
    	return $this->belongsToMany(Compra::Class);
    }
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use App\Producto;
use Illuminate\Http\Request;
use Image;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
class ProductoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    
    public function index()
    {
        $producto= Producto::paginate(10);

        return view ('productos.indexProductos', compact('producto'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view("productos.formProductos");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $producto = new Producto(); 

        //Proceso para las imagenes de los productos

        $this->validate($request,['photo'=>'required|image']);

        $imagen = $request->file('photo');
        $extension= $imagen->getClientOriginalExtension();
        $file_name= $this->random_string() . '.' . $extension;

        Image::make($imagen)
            ->resize(144,144)
            ->save('img/productos/'.$file_name);

        $producto->photo = $file_name;

        $request->validate([
          'nombre' => 'required|min:5',
          'descripcion' => 'required|min:10',
          'existencia' => 'required|integer',
          'cantidad' => 'required|integer',
          'precio' => 'required|integer'
        ]);

        $producto->Nombre = $request->nombre;
        $producto->Descripcion = $request->descripcion;
        $producto->Cantidad = $request->cantidad;
        $producto->Existencia = $request->existencia;
        $producto->Precio = $request->precio;

        $producto->save();

        return redirect()->route('producto.index')->with(['mensaje' => 'Producto Registrado', 'alert-class' => 'alert-success']);
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function show(Producto $producto)
    {
        //$producto = Producto::All();
        return view ('productos.showProductos', compact('producto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function edit(Producto $producto)
    {
        return view('productos.formProductos')->with(['producto' => $producto]);


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Producto $producto)
    {

        Producto::where('id', $producto->id)->update($request->except('_token', '_method'));
      
        return redirect()->route('producto.show', $producto->id);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Producto  $producto
     * @return \Illuminate\Http\Response
     */
    public function destroy(Producto $producto)
    {
        $producto->delete();
        return redirect()->route('producto.index');
    }


    
/*    public function getPhoto($request){
        if ($request->photo)
            return 'img/productos/'.$request->id.'.'.$request->photo;

        return 'img/productos/signo.jpg';
    }
    */

    protected function random_string(){
        $key = '';
        $keys = array_merge( range('a','z'), range(0,9) );
 
        for($i=0; $i<10; $i++){
            $key .= $keys[array_rand($keys)];
        }
 
            return $key;
    }

    public function buscar(Request $request){
        $datos = $request->busqueda;
        $producto = Producto::where('nombre', 'like','%'.$datos.'%')->paginate(10);

        return view ('productos.searchProductos', compact('producto'));
    }
}

resources/views/productos/formProductos.blade.php
@extends ('layouts.tema')
@section('contenido')

    <div class="row">
      <div clas="col-md-12">
          <div class="tile">
           @if(isset($producto))
       
         <form action="{{ route('producto.update', $producto->id) }}" method="POST"> 
         <input type="hidden" name="_method" value="PATCH"> 
      @else
       
          <form action="{{ route('producto.store') }}" method="POST" enctype="multipart/form-data">
      @endif
       
            {{ csrf_field() }}
         
            @if ($errors->any())
                <div class="alert alert-danger">
                   <ul>
                      @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                      @endforeach
                    </ul>
                </div>
            @endif

           
            
             <div class="form-group">
                <label for="nombre">Nombre Producto</label>
                <input name ="nombre" class="form-control" type="text">
             </div>
            
             <div class="form-group">
                <label for="descripcion">Descripcion</label>
                <textarea name="descripcion" class="form-control" type="text"> </textarea>
                
             </div>
            
             <div class="form-group">
                <label for="cantidad">Cantidad</label>
                <input name="cantidad" class="form-control" type="text">
         
             </div>

             <div class="form-group">
                <label for="existencia">Existencia</label>
                <input name="existencia" class="form-control" type="text">
             </div>

             <div class="form-group">
                <label for="precio">Precio</label>
                <input name="precio" class="form-control" type="text">
             </div>

             <div class ="form-goup">
                 <input name="photo" type="file" class="form-control" required>
             </div>
            
            <div class="tile-footer">
              <button class="btn btn-primary" type="submit">Agregar</button>
            </div>
            
          </form>
        </div>
      </div>
    </div>

@endsection

resources/views/productos/indexProductos.blade.php
@extends ('layouts.tema')
@section('contenido')

<div class="row">
  <div class="col-md-12">
    <table>
      <thead>
        <tr>
         

          <th>Nombre</th>
          <th>Descripcion</th>
          <th>Precio</th>

            
        </tr>
      </thead>

      <tbody>
        @foreach($producto as $prod)
          <tr>
  
            <td width="100">{{ $prod->nombre }}</td>  
            <td width="100">{{ $prod->descripcion }} </td>
            <td width="100">{{ $prod->precio }} </td> 
            <td> 
              <img src="/img/productos/{{$prod->photo}}" alt="imagen producto" class="w3->round"> 
            </td>
            <td>
              <a class="btn btn-sm bt-info btn-primary" href ="{{route('producto.show', $prod->id)}}"> Ver Detalle </a>
            </td>
             
          </tr>
          <td>
        
                
        @endforeach
      </tbody>
    </table>

             {{$producto->links()}}

     

  </div>

</div>

@endsection

resources/views/productos/searchProductos.blade.php
@extends ('layouts.tema')
@section('contenido')

<div class="row">
  <div class="col-md-12">
    <table>
      <thead>
        <tr>
          <th>  </th>
          <th>Nombre</th>
          <th>Descripcion</th>
          <th>Precio</th>
        </tr>
      </thead>

      <tbody>
        @foreach($producto as $prod)
          <tr>
            <td>
              <a class="btn btn-sm bt-info btn-primary" href ="{{route('producto.show', $prod->id)}}"> Ver Detalles </a>
            </td>

            <td>{{ $prod->nombre }}</td>  
            <td>{{ $prod->descripcion }} </td>
            <td>{{ $prod->precio }} </td> 
            <td> 
              <img src="/img/productos/{{$prod->photo}}" alt="imagen producto" class="w3->round"> 
            </td>
          </tr>
          
        @endforeach
      </tbody>
    </table>
    {{$producto->links()}}
  </div>

</div>

@endsection

resources/views/productos/showProductos.blade.php
@extends ('layouts.tema')
@section('contenido')
<div class="row">
  <div class="col-md-12">
    <table>
      <thead>
        <tr>
          <th>ID </th>
          <th>Nombre</th>
          <th>Descripcion</th>
          <th>Cantidad</th>
          <th>Existencia</th>
          <th>Precio</th>
        </tr>
      </thead>

      <img src="/img/productos/{{$producto->photo}}" alt="imagen producto" class="w3->round">
      <tbody>
        
          <tr>

            <td>{{ $producto->id }}</td>
            <td>{{ $producto->nombre }}</td>
            <td>{{ $producto->descripcion }}</td>
            <td>{{ $producto->cantidad }}</td>
            <td>{{ $producto->existencia }}</td>
            <td>{{ $producto->precio }}</td>

          </tr>
        
      </tbody>
    </table>

    <a class="btn btn-warning" href="{{ route('producto.edit', $producto->id) }}">Editar</a>
                <hr>

     <form action="{{ route('producto.destroy', $producto->id) }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>

    

    <form action="{{route ('venta.producto', $producto->id)}}", method="POST">
      {{ csrf_field() }}
      <input type="hidden" name="precio" value="{{$producto->precio}}">
      <button type="submit" class="btn btn-danger">Comprar</button>
    </form>
  </div>

</div>

@endsection